### ISSUE TITLE
Doesn't work in Cyberpunk with HDR on

### ISSUE THREAD

**Issue by bennasar99** [Nukem9/dlssg-to-fsr3#4] opened 2023-12-17 22:35 UTC
First of all, thanks for this! :)

My only problem is that Cyberpunk crashes on launch with this mod and HDR enabled (in game, with Windows AutoHDR it works fine).

I hope it gets fixed in future releases.

**Comment by ForthtuN** [comment] 2023-12-17 22:45
Figured it was the HDR that was crashing it. Hopefully gets fixed, so used to HDR that without it games look like shit hehe

**Comment by Calinou** [comment] 2023-12-18 17:27
- Duplicate of https://github.com/Nukem9/dlssg-to-fsr3/issues/14.

**Comment by TheWoodsy** [comment] 2023-12-19 06:22
Win11, 3090, CP2077
HDR works with 0.50

**Closed** 2023-12-19 16:52 UTC

**Comment by Nitro2137** [comment] 2024-01-09 00:32
Does not work with HDR on in Cyberpunk, tested 0.5, 0.6, 0.7, 0.8. 

You can turn it on, it loads, the framerate meter measures as if it is working (60% increase from non-fg), but the perceived smoothness remains as if it is off (halved/doubled frames effect). Back to dlss-fg - fully functional. 

FSR3 doesn't have reflex mismatch issues (significantly lower gpu utilization), uses less vram than DLSS-FG and has a slightly better frame rate in general. But for Cyberpunk 2077 in my setup it only works in SDR as intended. I've tried all the fixes available here and there, including CFG exclusions, firewall exclusions, DDU, nvcp vsync/reflex tweaks, so I can say with high confidence that it doesn't work in HDR. The SDR experience is excellent tho (with fsr3's own flaws, but that's another topic).

**Comment by RikkTheGaijin** [comment] 2024-02-04 08:00
I can confirm that in CP2077 when HDR is ON, the FPS shows like the mod it's working, but just by moving the camera around it's clear that it's not. Please fix it! CP in HDR looks so much better...
