### ISSUE TITLE
Horizon Forbidden West FG conflicts with Upscaler

### ISSUE THREAD

**Issue by Vladzor87do** [Nukem9/dlssg-to-fsr3#405] opened 2024-03-21 22:27 UTC
Even if Afterburner shows a 2x increase in FPS, in fact it is not felt, since frame generation conflicts with any upscaler method; DLAA and SMAA.

Only TAA ist working with DLSS FG and even this seems not to work properly

**Comment by Aidorin0** [comment] 2024-03-22 10:45
The same happens with Miles Morales (but not with Spider-Man 1, which works fine). Both also Nixxes ports.

**Comment by morgan-blondellet** [comment] 2024-03-22 11:39
DLAA and SMAA are not upsacling methods, those are antialiasing methods. DLSS and FSR are the upscalers

**Comment by ImASadBoy** [comment] 2024-03-22 19:16
I cannot reproduce this issue in any way, I made a friend of mine try and the issue was not there either, can you explain better?

**Comment by i5x64BIT** [comment] 2024-03-22 21:17
I would say the issue is wrong, the cause of this issue is uknown since all games that use dlss have dlaa.

The issue tho is the fact that you are running high frame rates but it fills more stuttry.

I run a 4k res with 3080ti and i7 12th gen chip, 32ram. baseline for dlss balanced is 70-90.
FG cranks the frames to 110, frametime is great but the movement feels worse then having 80 frames with FG off.

to reproduce try spining around while looking at one spot, you will see the image "jump" as if it skips a frame.

**Comment by ImASadBoy** [comment] 2024-03-22 23:19
I just confirmed everything works fine, I locked the game at 60fps, and captured my screen at 69fps, with FG on, every frame is different so there's no duplication going on, i tried every combination between SMAA, DLSS, DLAS, TAA, FSR

**Comment by Githubber954** [comment] 2024-03-23 02:39
I'm seeing similar results as OP. DLSS+FG is definitely not working. It looks just like running at the base fps. DLAA+FG looks smoother but still a little jittery. Only TAA+FG is working properly. On Steam there're multiple reports claiming FG doesn't feel smooth for 40 series users. So there's a chance the compatibility issue is unrelated to the mod.

**Comment by ecstra** [comment] 2024-03-23 09:47
FG is not working with anti-aliasing and upscaler turned on in this game for some reason unknown.

**Comment by darthmalak1986** [comment] 2024-03-24 00:57
using nuke 9 is giving ui ghosting :( but nuke dissapear

**Comment by lightniing1** [comment] 2024-03-24 05:42
In Horizon Forbidden West, the mod actually gives lower fps and shimmering in motion. It also breaks the in-game Dynamic Resolution Scaling (DRS).

This all happens with frame generation **OFF**. With it on, it increases the FPS (I can see in the monitor settings and in RTSS) but with the same problem as above (except the DRS problem, since it gets disabled with frame gen on) + really bad frame pacing.

PC Specs:

AMD Ryzen 5 7600
RTX 3080 10GB
Monitor ÇG 27gr95qe-b

I forced rBAR on using the Nvidia Profile Inspector for the game and it gave me a huge FPS boost (more than 25fps (!!!) in all scenarios i could test)

I tested the mod with rBAR on and off, but the same results.

I suggest for now to NOT use the mod. If you don't have frame generation ON and the mod **still** in the folder, DELETE IT. It breaks the in-game DRS and lowers your fps. 

All we can do now is wait.

**Comment by darthmalak1986** [comment] 2024-03-24 16:59
did you try lossless scaling? is working for me or at least that what i think

**Comment by skurukulasuriya** [comment] 2024-03-27 03:37
Don't use Nvidia reflex setting with boost. My game doesn't stutter with just reflex on but it will start to stutter if i use both on + boost.

**Comment by Nukem9** [comment] 2024-03-27 09:48
Settings tested:
* Display Resolution: 2560x1440
* Window Mode: Fullscreen
* Reflex Low Latency: On (I checked On + Boost, it makes no difference)
* dlssg-to-fsr3 used in place of Nvidia frame generation on a RTX 2080 Ti

Real frame vs interpolated frame comparisons:
* No antialiasing, no upscaling, FG on: https://imgsli.com/MjUwNjQw
* DLAA antialiasing, no upscaling, FG on: https://imgsli.com/MjUwNjQx
* DLSS antialiasing, DLSS upscaling (quality), FG on: https://imgsli.com/MjUwNjQz

It works as expected, at least on my computer. I haven't been able to figure out why only some people are having issues. Maybe a setting I'm not accounting for?

VRAM pressure/exhaustion also leads to stutter. I can't fix that unfortunately.

**Comment by Githubber954** [comment] 2024-03-28 06:18
^Since it's indeed working on your end judging by the DLSS hud ghosting on the bottom left corner, I tried troubleshooting again and perhaps found the culprit. I set DLSSPresets in DLSSTweaks back to default and FG is working with DLSS. It's now just as smooth as TAA and the DLSS hud is "properly" ghosting. So perhaps changing DLSSPresets conflicts with FG in this game (I know  DLSSQualityLevels will interfere with the in game DRS, but this one's unrelated to FG).

**Comment by evancolt** [comment] 2024-03-28 16:43
After turning off RTSS for HFW, I've found frame gen works properly with your mod and others.

**Comment by ajmi982** [comment] 2024-03-28 16:51
> After turning off RTSS for HFW, I've found frame gen works properly with your mod and others. Just tried it with and without, turning it off makes the mod work. I'm 100% sure this is causing others issues since many people (including me) use RTSS on every game.
> 
> Also the game had an update today with one piece mentioning Frame Gen: "DLSS 3 Frame Generation is now active in cutscenes and while UI screens such as the weapon wheel are displayed."

RTSS needs to be fully shut down? Closed?

or can you have stealth mode or application detection level set to low/none?

wondering if any type of setting in RTSS resolves the issue to still enable overlays. 

Also, any chance the NVIDIA overlay is causing issue?

**Comment by evancolt** [comment] 2024-03-28 16:54
> > After turning off RTSS for HFW, I've found frame gen works properly with your mod and others. Just tried it with and without, turning it off makes the mod work. I'm 100% sure this is causing others issues since many people (including me) use RTSS on every game.
> > Also the game had an update today with one piece mentioning Frame Gen: "DLSS 3 Frame Generation is now active in cutscenes and while UI screens such as the weapon wheel are displayed."
> 
> RTSS needs to be fully shut down? Closed?
> 
> or can you have stealth mode or application detection level set to low/none?
> 
> wondering if any type of setting in RTSS resolves the issue to still enable overlays.
> 
> Also, any chance the NVIDIA overlay is causing issue?

I made a rule in RTSS for detection set to NONE. RTSS is not closed as it runs on other games. NVIDIA overlay seems to work fine, I'm using that as a replacement for RTSS.

**Comment by BanefulDemon** [comment] 2024-03-28 17:17
Do you have the new 7.3.6 version of RTSS? I think that was supposed to fix the performance degradation for HFW.

**Comment by evancolt** [comment] 2024-03-28 17:19
> Do you have the new 7.3.6 version of RTSS? I think that was supposed to fix the performance degradation for HFW.

I do not. I'll try it out and report back and edit this post.

**Comment by ajmi982** [comment] 2024-03-28 17:29
Could we also just go into the registry and set ReflexMode to 0?

**Comment by ajmi982** [comment] 2024-03-28 17:36
> > Do you have the new 7.3.6 version of RTSS? I think that was supposed to fix the performance degradation for HFW.
> 
> I do not. I'll try it out and report back and edit this post.
> 
> EDIT: updating RTSS seems to have fixed the issue. Will need more testing than me of course, but so far seems to be good after a few minutes.

so Reflex is NOT an issue anymore (or never was) just update RTSS to 7.3.6?

**Comment by evancolt** [comment] 2024-03-28 18:09
> > > Do you have the new 7.3.6 version of RTSS? I think that was supposed to fix the performance degradation for HFW.
> > 
> > 
> > I do not. I'll try it out and report back and edit this post.
> > EDIT: updating RTSS seems to have fixed the issue. Will need more testing than me of course, but so far seems to be good after a few minutes.
> 
> so Reflex is NOT an issue anymore (or never was) just update RTSS to 7.3.6?

i never touched reflex. after updating RTSS to latest 7.3.6 it seems to work normally now using DLSS/FG

**Comment by ajmi982** [comment] 2024-03-28 18:52
Has anyone tried with this mod: https://github.com/ChieuNguyen2002/FSR2FSR3_MOD-Beta

seeing claims on reddit that FG works fine with no frametime issues and REFLEX on.

**Comment by darthmalak1986** [comment] 2024-03-29 09:30
> Has anyone tried with this mod: fsr2fsr3 (LINK HAS BEEN REMOVED BY @Nukem9 FOR PIRACY)
> 
> seeing claims on reddit that FG works fine with no frametime issues and REFLEX on.

That one is from lukefz. Is not a mod actually from him is someone else sharing his files.

My suggestion that is actually working with no issues is to use lossless scaling (paid version ) the "illegal" one its gives alt tabbing issues .

But believe me that paying for lossless scaling it is worth it , I haves input lag or lag with lukefz over horizon forbidden west , plus random crashes .plus rtss overlay crashing, you have to play around to see if it works and plus and CMD window over there bothering you out .

Lossless scaling is easier you just use no scaling type , put there lsfg if you want you can add the exe to the program to auto scalate and boom working with no issues no ui ghosting or anything else .

Just make sure that you can archive 50+ fps or 60 steady otherwise it will be warping and is annoying 

It is worth it is just cost 3us ppl I'm not promoting his stuff I'm just saying it is worth it and you can used in every game 

Wish @Nukem9 could do his own cause his method is also easier, clean no window , no cmd and you just press activate frame g and done . And plus with Nuke it allow you to you Ray reconstruct from Nvidia , he's awesome 

But sadly I don't know maybe his working or improving sownrhing or bussy I wish he could make this better and easier just lossless did .

You're awesome nuke!!!!

**Comment by Vladzor87do** [comment] 2024-03-29 15:16
Guys even if RTSS if off its still not working, you can check yourself, just cap max framerate at NVIDIA driver to 120 and test yourself turn on DLSS and FG and turn off FG, you will see that FG is still broken even with RTSS off

**Comment by LeBlackMeow** [comment] 2024-03-29 17:29
Nukem itself said that the frame pacing is messed up. And I'm sure that his testes were more thorough than any of you.

**Comment by Vladzor87do** [comment] 2024-03-29 17:51
> Nukem itself said that the frame pacing is messed up. And I'm sure that his testes were more thorough than any of you.

no one asked you personally for your opinion

**Closed** 2024-03-29 17:51 UTC

**Comment by ziomek64** [comment] 2024-03-30 07:22
I also have higher fps with frame gen on but it feels off a lot

**Comment by darthmalak1986** [comment] 2024-03-30 08:48
> Guys even if RTSS is off its still not working, you can check yourself, just cap max framerate at NVIDIA driver to 120 and test yourself turn on DLSS and FG and after that turn off FG, you will see the difirence that FG is still broken even with RTSS off
> 
> With FG off its 120 fps FG on it caps fps to 60, you can feel low framerate,
> 
> Looks like FG is just skipping frames, this can be seen from powerconsumtion:
> 
> With my undervolted RTX3080 @ 0.818v caped at 120 fps DLSS ON + FG OFF - 190 watts caped at 120 fps DLSS ON + FG ON - 140 watts

What someone explained to you . You didn't ubdetsbd at all .

You shouldn't not our whatever cap to whatever ppl because you don't know what monitor Hz they have 

The correct solution for that Is:

Cap your fps to half of your monitor Hz 

If your monitor can show 144hz limit just your fps to half and activate frame g . That will give you your total fps

Apply same scenario to whatever monitor Hz that everyone has .

Why ?bcoz you're just wasting GPU load

You need to run the game at 50ish or 60 (60 ad base is recommended) to avoid having warping

But I'm surprised that no one noticed input lag ? Or no one is feeling it or not even aware of it using lukefz I'm surprised that in alone saying all of that 

Also update dlss and frame g dll that should improve fps a bit . Those files are over nexusmod mod ( all you need to do is to replace those files nothing else )

Also do not use tfaa if you're at your max resolution and it will conflict with frame generation ( sometimes )replaced it if you needed it with dlaa over reshade and your problem should be fixed (some time's using the anti alissikf of the game it coles with issued with frame generation)

Also for winning fps you can lower clouds to low as hair if you want and out reflex to on or maybe off .

I think on plus oc it will give a penalize

And leave the rest as they are (anyways there is no difference with the clouds) maybe just an extra detailed cloud haha

**Comment by Vladzor87do** [comment] 2024-03-31 22:10
> > Guys even if RTSS is off its still not working, you can check yourself, just cap max framerate at NVIDIA driver to 120 and test yourself turn on DLSS and FG and after that turn off FG, you will see the difirence that FG is still broken even with RTSS off
> > With FG off its 120 fps FG on it caps fps to 60, you can feel low framerate,
> > Looks like FG is just skipping frames, this can be seen from powerconsumtion:
> > With my undervolted RTX3080 @ 0.818v caped at 120 fps DLSS ON + FG OFF - 190 watts caped at 120 fps DLSS ON + FG ON - 140 watts
> 
> What someone explained to you . You didn't ubdetsbd at all .
> 
> You shouldn't not our whatever cap to whatever ppl because you don't know what monitor Hz they have
> 
> The correct solution for that Is:
> 
> Cap your fps to half of your monitor Hz
> 
> If your monitor can show 144hz limit just your fps to half and activate frame g . That will give you your total fps
> 
> Apply same scenario to whatever monitor Hz that everyone has .
> 
> Why ?bcoz you're just wasting GPU load
> 
> You need to run the game at 50ish or 60 (60 ad base is recommended) to avoid having warping
> 
> But I'm surprised that no one noticed input lag ? Or no one is feeling it or not even aware of it using lukefz I'm surprised that in alone saying all of that
> 
> Also update dlss and frame g dll that should improve fps a bit . Those files are over nexusmod mod ( all you need to do is to replace those files nothing else )
> 
> Also do not use tfaa if you're at your max resolution and it will conflict with frame generation ( sometimes )replaced it if you needed it with dlaa over reshade and your problem should be fixed (some time's using the anti alissikf of the game it coles with issued with frame generation)
> 
> Also for winning fps you can lower clouds to low as hair if you want and out reflex to on or maybe off .
> 
> I think on plus oc it will give a penalize
> 
> And leave the rest as they are (anyways there is no difference with the clouds) maybe just an extra detailed cloud haha

You dont even undersand what I was trying to test

**Comment by darthmalak1986** [comment] 2024-04-01 08:40
Who said I didn't?

I do I understand that you're trying to be able to fix the issues over fg.

Dunno why you keep complaining when the solution is easier just use lossless scaling 

...sometimes over complicating things is not that helpful

Until nuke does snorting bout it

But I think he is out

**Comment by darthmalak1986** [comment] 2024-04-01 08:41
@Nukem9 buddy did you quit your project?

Or you're working on an any update?

There is something you can share with us?

**Comment by Bogo36** [comment] 2024-04-15 14:25
For the people who have problems with framepacing:
Set the sharpness in the graphic options to zero!
There is something wrong with this option.

Now you can use FG and TAA or DLAA without bad framepacing.
SMAA is still broken.

DLSS and FSR doesnt feel smooth, but Intel Xess feals not bad.

**Comment by Githubber954** [comment] 2024-04-16 15:41
I think the confusion comes from people targeting different frame rates. At 100+fps it's harder to notice the frame pacing issue with DLAA/DLSS+FG. At 90fps only TAA+FG looks smooth in motion.

**Comment by Bogo36** [comment] 2024-04-16 17:15
> I think the confusion comes from people targeting different frame rates. At 100+fps it's harder to notice the frame pacing issue with DLAA/DLSS+FG. At 90fps only TAA+FG looks smooth in motion.

My target is about 120-130 FPS and with sharpness set to zero and nvidia reflex set to the lowest, DLAA is now also looking smooth. DLSS and FSR are also better, but Intel Xess feels somehow the smoothest.
I swear, something is wrong with the sharpness and the reflex setting.
